"""LLM Service for Huawei Cloud MaaS integration.

MaaS provides an OpenAI-compatible API, so we use the openai library
with custom base URL and API key.
"""

from openai import OpenAI
from app.config import load_config
from typing import List, Dict, Optional, Generator


class LLMService:
    """Service for interacting with Huawei Cloud MaaS LLM."""

    def __init__(self):
        self._client: Optional[OpenAI] = None
        self._config_key: Optional[str] = None  # track which key the client was built with

    def _get_client(self) -> OpenAI:
        """Get or create the OpenAI client configured for MaaS (cached)."""
        config = load_config()

        if not config.maas.url or not config.maas.api_key:
            raise ValueError(
                "MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )

        # Reuse existing client if the API key hasn't changed
        if self._client is not None and self._config_key == config.maas.api_key:
            return self._client

        # Ensure URL ends with /v1 for OpenAI compatibility
        base_url = config.maas.url.rstrip("/")
        if not base_url.endswith("/v1"):
            base_url = base_url + "/v1"

        self._client = OpenAI(
            api_key=config.maas.api_key,
            base_url=base_url
        )
        self._config_key = config.maas.api_key
        return self._client

    def generate_response(
        self,
        query: str,
        context_documents: List[str]
    ) -> str:
        """Generate a response using RAG (Retrieval-Augmented Generation).

        Args:
            query: The user's question.
            context_documents: Retrieved documents from ChromaDB to use as context.

        Returns:
            The generated response from the LLM.
        """
        config = load_config()

        if not config.maas.url or not config.maas.api_key or not config.maas.model:
            return (
                "⚠️ MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )

        client = self._get_client()
        system_prompt = self._build_system_prompt(context_documents)

        try:
            response = client.chat.completions.create(
                model=config.maas.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                temperature=0.7,
                max_tokens=2048
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"❌ Error al comunicarse con MaaS: {str(e)}"

    def generate_response_stream(
        self,
        query: str,
        context_documents: List[str]
    ) -> Generator[str, None, None]:
        """Generate a streaming response using RAG.

        Yields chunks of text as they are generated by the LLM,
        allowing the frontend to display tokens incrementally.

        Args:
            query: The user's question.
            context_documents: Retrieved documents from ChromaDB to use as context.

        Yields:
            Text chunks as they arrive from the LLM.
        """
        config = load_config()

        if not config.maas.url or not config.maas.api_key or not config.maas.model:
            yield (
                "⚠️ MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )
            return

        client = self._get_client()
        system_prompt = self._build_system_prompt(context_documents)

        try:
            stream = client.chat.completions.create(
                model=config.maas.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                temperature=0.7,
                max_tokens=2048,
                stream=True
            )
            for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content
        except Exception as e:
            yield f"\n\n❌ Error al comunicarse con MaaS: {str(e)}"

    @staticmethod
    def _build_system_prompt(context_documents: List[str]) -> str:
        """Build the system prompt with the Lykos persona and optional RAG context."""

        lykos_persona = (
            "[ROL]\n"
            "Eres \"Lykos\", un asistente virtual de alto nivel para LYKOS SI CONSULTING, "
            "una consultora de ciberseguridad de élite. Tu personalidad es profesional, "
            "inteligente, cercana y proactiva. Hablas de forma clara, directa y humana, "
            "evitando a toda costa sonar como un robot o una máquina de respuestas automáticas.\n\n"

            "[OBJETIVO PRINCIPAL]\n"
            "Brindar asistencia sobre ciberseguridad, resolver dudas sobre los servicios de "
            "la empresa y guiar sutilmente al usuario hacia la contratación de servicios o "
            "agendar una reunión. Bajo ninguna circunstancia debes dejar que la conversación muera.\n\n"

            "[REGLAS ESTRICTAS DE COMPORTAMIENTO]\n"
            "1. PROHIBIDO DECIR \"NO SÉ\" O \"NO PUEDO\": Nunca uses frases como "
            "\"No tengo suficiente información\", \"No estoy programado para eso\", "
            "\"Solo puedo responder sobre...\", \"No hay información disponible\". "
            "Estas frases están terminantemente prohibidas.\n\n"

            "2. TÉCNICA DE REDIRECCIÓN (Para temas fuera de contexto): Si el usuario pregunta "
            "sobre algo ajeno a la ciberseguridad (ej. el clima, deportes, recetas, cultura general), "
            "debes usar la fórmula: [Afirmar tu enfoque] + [Ofrecer ayuda en tu área]. "
            "Ejemplo: En lugar de decir \"No sé sobre el clima\", di: \"Mi especialidad y pasión "
            "es el mundo de la ciberseguridad. Si tienes dudas sobre cómo proteger tus datos o "
            "necesitas una auditoría, puedo ayudarte con eso. ¿Te gustaría saber sobre nuestros servicios?\"\n\n"

            "3. TONO HUMANO: Usa conectores naturales, variedades del idioma (tú/usted según "
            "cómo te hablen) y empatía. No uses lenguaje excesivamente técnico a menos que el "
            "usuario lo haga primero.\n\n"

            "4. PROACTIVIDAD: Siempre termina tus respuestas con una pregunta abierta o una "
            "llamada a la acción suave (ej. \"¿Te gustaría agendar una llamada para evaluar tu caso?\", "
            "\"¿Necesitas más detalles sobre esto?\", \"¿Quieres que revisemos cómo esto aplica a tu empresa?\").\n\n"

            "5. REGLA ANTI-ALUCINACIONES (ALTA Y CRÍTICA) ⚠️: ESTÁ TERMINANTEMENTE PROHIBIDO "
            "INVENTAR, ADIVINAR O ALUCINAR CUALQUIER TIPO DE DATO PRECISO. Si no tienes un dato "
            "exacto en tu base de conocimientos, NUNCA lo inventes. Queda estrictamente prohibido "
            "inventar lo siguiente:\n"
            "   - Correos electrónicos (ej. info@...).\n"
            "   - Enlaces web, URLs o enlaces de Calendly.\n"
            "   - Números de teléfono.\n"
            "   - Precios exactos, tarifas o facturaciones.\n"
            "   - Datos técnicos exactos (versiones de software, puertos específicos, configuraciones "
            "de firewall, cifrados exactos, etc.).\n"
            "Si piden datos técnicos muy específicos o datos de contacto, sugiere que lo mejor sería "
            "comunicarse con un experto de LYKOS y proporciona los datos de contacto reales que "
            "tengas en tu base de conocimientos. Si no tienes los datos de contacto en tu base, "
            "di: \"Te recomiendo comunicarte directamente con nuestro equipo de LYKOS SI CONSULTING "
            "para obtener esa información precisa. ¿Te gustaría que te indique cómo contactarnos?\"\n\n"

            "[INFORMACIÓN DE CONTEXTO]\n"
        )

        if context_documents:
            context_text = "\n\n---\n\n".join(context_documents)
            return (
                f"{lykos_persona}"
                "A continuación tienes información verificada sobre LYKOS SI CONSULTING y sus servicios. "
                "Usa esta información como base para tus respuestas, pero siempre manteniendo tu personalidad "
                "de Lykos — cercano, profesional y proactivo.\n\n"
                f"Información disponible:\n{context_text}"
            )

        return (
            f"{lykos_persona}"
            "No se encontró información específica en la base de datos para esta consulta, "
            "pero eso NO significa que no puedas ayudar. Usa tu conocimiento general sobre "
            "ciberseguridad y los servicios de LYKOS SI CONSULTING para orientar al usuario. "
            "Si el tema es muy específico, ofrece agendar una reunión con un experto."
        )


# Singleton instance
llm_service = LLMService()
