"""LLM Service for Huawei Cloud MaaS integration.

MaaS provides an OpenAI-compatible API, so we use the openai library
with custom base URL and API key.
"""

from openai import OpenAI
from app.config import load_config
from typing import List, Dict, Optional, Generator


class LLMService:
    """Service for interacting with Huawei Cloud MaaS LLM."""

    def __init__(self):
        self._client: Optional[OpenAI] = None
        self._config_key: Optional[str] = None  # track which key the client was built with

    def _get_client(self) -> OpenAI:
        """Get or create the OpenAI client configured for MaaS (cached)."""
        config = load_config()

        if not config.maas.url or not config.maas.api_key:
            raise ValueError(
                "MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )

        # Reuse existing client if the API key hasn't changed
        if self._client is not None and self._config_key == config.maas.api_key:
            return self._client

        # Ensure URL ends with /v1 for OpenAI compatibility
        base_url = config.maas.url.rstrip("/")
        if not base_url.endswith("/v1"):
            base_url = base_url + "/v1"

        self._client = OpenAI(
            api_key=config.maas.api_key,
            base_url=base_url
        )
        self._config_key = config.maas.api_key
        return self._client

    def generate_response(
        self,
        query: str,
        context_documents: List[str]
    ) -> str:
        """Generate a response using RAG (Retrieval-Augmented Generation).

        Args:
            query: The user's question.
            context_documents: Retrieved documents from ChromaDB to use as context.

        Returns:
            The generated response from the LLM.
        """
        config = load_config()

        if not config.maas.url or not config.maas.api_key or not config.maas.model:
            return (
                "⚠️ MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )

        client = self._get_client()
        system_prompt = self._build_system_prompt(context_documents)

        try:
            response = client.chat.completions.create(
                model=config.maas.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                temperature=0.7,
                max_tokens=2048
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"❌ Error al comunicarse con MaaS: {str(e)}"

    def generate_response_stream(
        self,
        query: str,
        context_documents: List[str]
    ) -> Generator[str, None, None]:
        """Generate a streaming response using RAG.

        Yields chunks of text as they are generated by the LLM,
        allowing the frontend to display tokens incrementally.

        Args:
            query: The user's question.
            context_documents: Retrieved documents from ChromaDB to use as context.

        Yields:
            Text chunks as they arrive from the LLM.
        """
        config = load_config()

        if not config.maas.url or not config.maas.api_key or not config.maas.model:
            yield (
                "⚠️ MaaS no está configurado. Verifique las variables de entorno "
                "en el archivo .env (MAAS_URL, MAAS_API_KEY, MAAS_MODEL)."
            )
            return

        client = self._get_client()
        system_prompt = self._build_system_prompt(context_documents)

        try:
            stream = client.chat.completions.create(
                model=config.maas.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                temperature=0.7,
                max_tokens=2048,
                stream=True
            )
            for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content
        except Exception as e:
            yield f"\n\n❌ Error al comunicarse con MaaS: {str(e)}"

    @staticmethod
    def _build_system_prompt(context_documents: List[str]) -> str:
        """Build the system prompt with optional RAG context."""
        if context_documents:
            context_text = "\n\n---\n\n".join(context_documents)
            return (
                "Eres un asistente útil y preciso. Responde las preguntas del usuario "
                "basándote EXCLUSIVAMENTE en la siguiente información proporcionada. "
                "Si la información proporcionada no es suficiente para responder la pregunta, "
                "indica claramente que no hay suficiente información disponible.\n\n"
                f"Información disponible:\n{context_text}"
            )
        return (
            "Eres un asistente útil y preciso. No hay información disponible en la base "
            "de datos para responder la pregunta del usuario. Indica amablemente que "
            "no hay información en ChromaDB para responder su consulta."
        )


# Singleton instance
llm_service = LLMService()
